"""DRAFT FOR HUMAN REVIEW: not reviewed by teammates or a diverse volunteer panel.

A deterministic screening layer, not a guarantee of respectful model output.
"""

ALLOWED_FEATURES = frozenset(("smile", "expression", "eyes", "presence", "style"))
FEATURE_KEYWORDS = {
    "smile": ("smile", "smiling"),
    "expression": ("expression", "expressive"),
    "eyes": ("eyes", "gaze"),
    "presence": ("presence", "energy", "calm"),
    "style": ("style", "glasses", "hat", "pattern"),
}
DENY_CATEGORIES = {
    "age": (
        "young",
        "old",
        "youthful",
        "age",
        "aged",
        "mature",
        "elderly",
        "teen",
        "child",
        "adult",
    ),
    "body": (
        "thin",
        "slim",
        "skinny",
        "fat",
        "weight",
        "curvy",
        "figure",
        "body",
        "sexy",
    ),
    "skin_ethnicity": (
        "skin",
        "complexion",
        "tan",
        "pale",
        "ethnic",
        "ethnicity",
        "race",
        "racial",
        "exotic",
        "asian",
        "white",
        "black",
    ),
    "gender": (
        "he",
        "she",
        "him",
        "her",
        "his",
        "hers",
        "man",
        "woman",
        "boy",
        "girl",
        "guy",
        "sir",
        "ma'am",
        "handsome",
        "pretty",
        "beautiful",
        "masculine",
        "feminine",
        "gender",
        "sexy",
    ),
    "health": (
        "disabled",
        "disability",
        "healthy",
        "health",
        "ill",
        "sick",
        "blind",
        "deaf",
        "autistic",
        "depressed",
        "diagnosis",
        "disease",
    ),
}
BACKHANDED = (
    "than",
    "for a",
    "even though",
    "but",
    "unlike",
    "most people",
    "usually",
    "at least",
    "not",
    "no",
    "never",
    "best",
    "prettiest",
    "hottest",
    "ugly",
    "bad",
    "weird",
    "despite",
)
NEUTRAL_GREETINGS = ("It's good to see you today.", "Welcome. I'm glad you are here.")
